[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/items/all"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "lost-found-portal"

[services.variables]
SPRING_DATASOURCE_URL = "jdbc:mysql://containers-us-west-19.railway.app:6969/railway"
SPRING_DATASOURCE_USERNAME = "root"
SPRING_DATASOURCE_PASSWORD = "your-password"
SPRING_JPA_HIBERNATE_DDL_AUTO = "update"
SPRING_JPA_DATABASE_PLATFORM = "org.hibernate.dialect.MySQLDialect"
